--AP
TRUNCATE TABLE TAPTDoDT
TRUNCATE TABLE TAPTDoHD
TRUNCATE TABLE TAPTDoHDDocRef
TRUNCATE TABLE TAPTDoHDSpl
TRUNCATE TABLE TAPTPcDT
TRUNCATE TABLE TAPTPcHD
TRUNCATE TABLE TAPTPcHDSpl
TRUNCATE TABLE TAPTPiDT
TRUNCATE TABLE TAPTPiDTDis
TRUNCATE TABLE TAPTPiHD
TRUNCATE TABLE TAPTPiHDDis
TRUNCATE TABLE TAPTPiHDDocRef
TRUNCATE TABLE TAPTPiHDSpl
TRUNCATE TABLE TAPTPnDT
TRUNCATE TABLE TAPTPnDTDis
TRUNCATE TABLE TAPTPnHD
TRUNCATE TABLE TAPTPnHDSpl
TRUNCATE TABLE TAPTPoDT
TRUNCATE TABLE TAPTPoHD
TRUNCATE TABLE TAPTPoHDDocRef
TRUNCATE TABLE TAPTPoHDSpl
TRUNCATE TABLE TAPTPoMgtDT
TRUNCATE TABLE TAPTPoMgtHD
TRUNCATE TABLE TAPTPoMgtHDDoc
TRUNCATE TABLE TAPTPxDT
TRUNCATE TABLE TAPTPxDTDis
TRUNCATE TABLE TAPTPxHD
TRUNCATE TABLE TAPTPxHDDis
TRUNCATE TABLE TAPTPxHDDocRef
TRUNCATE TABLE TAPTPxHDSpl
TRUNCATE TABLE TARTRcvDepositDT
TRUNCATE TABLE TARTRcvDepositHD
TRUNCATE TABLE TARTRcvDepositHDCst
TRUNCATE TABLE TARTSoDT
TRUNCATE TABLE TARTSoDTDis
TRUNCATE TABLE TARTSoHD
TRUNCATE TABLE TARTSoHDCst
TRUNCATE TABLE TARTSoHDDis
TRUNCATE TABLE TARTSoHDDocRef
TRUNCATE TABLE TARTSpDT
TRUNCATE TABLE TARTSpHD
TRUNCATE TABLE TARTSpHDCst
TRUNCATE TABLE TARTSpHDDocRef
TRUNCATE TABLE TARTSpRC
TRUNCATE TABLE TARTSqDT
TRUNCATE TABLE TARTSqDTDis
TRUNCATE TABLE TARTSqHD
TRUNCATE TABLE TARTSqHDCst
TRUNCATE TABLE TARTSqHDDis
TRUNCATE TABLE TARTSqHDDocRef
--CENTER
TRUNCATE TABLE TCNMAddress_L
TRUNCATE TABLE TCNMAdMsg
TRUNCATE TABLE TCNMAdMsg_L
TRUNCATE TABLE TCNMAgency
TRUNCATE TABLE TCNMAgency_L
TRUNCATE TABLE TCNMAgencySpc
TRUNCATE TABLE TCNMAppModule
TRUNCATE TABLE TCNMArea
TRUNCATE TABLE TCNMArea_L

--TRUNCATE TABLE TCNMBranch
--TRUNCATE TABLE TCNMBranch_L


TRUNCATE TABLE TCNMChannel
TRUNCATE TABLE TCNMChannel_L
TRUNCATE TABLE TCNMChannelSpc
TRUNCATE TABLE TCNMCst
TRUNCATE TABLE TCNMCst_L
TRUNCATE TABLE TCNMCstAddress_L
TRUNCATE TABLE TCNMCstBch
TRUNCATE TABLE TCNMCstCard
TRUNCATE TABLE TCNMCstCredit
TRUNCATE TABLE TCNMCstGrp
TRUNCATE TABLE TCNMCstGrp_L
TRUNCATE TABLE TCNMCstLev
TRUNCATE TABLE TCNMCstLev_L
TRUNCATE TABLE TCNMCstType
TRUNCATE TABLE TCNMCstType_L
TRUNCATE TABLE TCNMFleObj
TRUNCATE TABLE TCNMImgObj
TRUNCATE TABLE TCNMImgPdt
TRUNCATE TABLE TCNMLimitRole
TRUNCATE TABLE TCNMLot
TRUNCATE TABLE TCNMMsgDT
TRUNCATE TABLE TCNMMsgHD
TRUNCATE TABLE TCNMMsgHD_L

--TRUNCATE TABLE TCNMNation
--TRUNCATE TABLE TCNMNation_L

TRUNCATE TABLE TCNMNews
TRUNCATE TABLE TCNMNews_L
TRUNCATE TABLE TCNMNewsBch
TRUNCATE TABLE TCNMOverDueLev
TRUNCATE TABLE TCNMPdt
TRUNCATE TABLE TCNMPdt_L
TRUNCATE TABLE TCNMPdtBar
TRUNCATE TABLE TCNMPdtBrand
TRUNCATE TABLE TCNMPdtBrand_L
TRUNCATE TABLE TCNMPdtCategory
TRUNCATE TABLE TCNMPdtCatInfo
TRUNCATE TABLE TCNMPdtCatInfo_L
TRUNCATE TABLE TCNMPdtColor
TRUNCATE TABLE TCNMPdtColor_L
TRUNCATE TABLE TCNMPdtCostAvg
TRUNCATE TABLE TCNMPdtGrp
TRUNCATE TABLE TCNMPdtGrp_L
TRUNCATE TABLE TCNMPdtLoc
TRUNCATE TABLE TCNMPdtLoc_L
TRUNCATE TABLE TCNMPdtLot
TRUNCATE TABLE TCNMPdtModel
TRUNCATE TABLE TCNMPdtModel_L
TRUNCATE TABLE TCNMPdtPackSize
TRUNCATE TABLE TCNMPdtPriList
TRUNCATE TABLE TCNMPdtPriList_L
TRUNCATE TABLE TCNMPdtSize
TRUNCATE TABLE TCNMPdtSize_L
TRUNCATE TABLE TCNMPdtSpcBch
TRUNCATE TABLE TCNMPdtSpcWah
TRUNCATE TABLE TCNMPdtSpl
TRUNCATE TABLE TCNMPdtType
TRUNCATE TABLE TCNMPdtType_L
TRUNCATE TABLE TCNMPdtUnit
TRUNCATE TABLE TCNMPdtUnit_L
TRUNCATE TABLE TCNMPos
TRUNCATE TABLE TCNMPos_L
TRUNCATE TABLE TCNMPosAds
TRUNCATE TABLE TCNMPosHW
TRUNCATE TABLE TCNMPrinter
TRUNCATE TABLE TCNMPrinter_L


--TRUNCATE TABLE TCNMProvince
--TRUNCATE TABLE TCNMProvince_L
--TRUNCATE TABLE TCNMQasGrp
--TRUNCATE TABLE TCNMQasGrp_L

TRUNCATE TABLE TCNMQasSubGrp
TRUNCATE TABLE TCNMQasSubGrp_L
TRUNCATE TABLE TCNMRsn
TRUNCATE TABLE TCNMRsn_L
TRUNCATE TABLE TCNMSlipMsgDT_L
TRUNCATE TABLE TCNMSlipMsgHD_L
TRUNCATE TABLE TCNMSpl
TRUNCATE TABLE TCNMSpl_L
TRUNCATE TABLE TCNMSplAddress_L
TRUNCATE TABLE TCNMSplCard
TRUNCATE TABLE TCNMSplCredit
TRUNCATE TABLE TCNMSplGrp
TRUNCATE TABLE TCNMSplGrp_L
TRUNCATE TABLE TCNMSplLev
TRUNCATE TABLE TCNMSplLev_L
TRUNCATE TABLE TCNMSplType
TRUNCATE TABLE TCNMSplType_L
TRUNCATE TABLE TCNMTaxAddress_L

TRUNCATE TABLE TCNMTxnAPI
TRUNCATE TABLE TCNMTxnAPI_L

--TRUNCATE TABLE TCNMWaHouse
--TRUNCATE TABLE TCNMWaHouse_L

TRUNCATE TABLE TCNMZone
TRUNCATE TABLE TCNMZone_L


--TRUNCATE TABLE TCNSLimitDT
--TRUNCATE TABLE TCNSLimitHD
--TRUNCATE TABLE TCNSLimitHD_L
--TRUNCATE TABLE TCNSListObj
--TRUNCATE TABLE TCNSListObj_L
--TRUNCATE TABLE TCNSPmtPdtCond
--TRUNCATE TABLE TCNSPmtPdtCond_L

TRUNCATE TABLE TCNTAutoHisMas
TRUNCATE TABLE TCNTAutoHisTxn

TRUNCATE TABLE TCNTMsgRemind
TRUNCATE TABLE TCNTPdtAdjCostDT
TRUNCATE TABLE TCNTPdtAdjCostHD
TRUNCATE TABLE TCNTPdtAdjPriDT
TRUNCATE TABLE TCNTPdtAdjPriHD
TRUNCATE TABLE TCNTPdtAdjStkDT
TRUNCATE TABLE TCNTPdtAdjStkHD
TRUNCATE TABLE TCNTPdtClaimDT
TRUNCATE TABLE TCNTPdtClaimDTRcv
TRUNCATE TABLE TCNTPdtClaimDTRet
TRUNCATE TABLE TCNTPdtClaimDTSpl
TRUNCATE TABLE TCNTPdtClaimDTWrn
TRUNCATE TABLE TCNTPdtClaimHD
TRUNCATE TABLE TCNTPdtClaimHDCst
TRUNCATE TABLE TCNTPdtClaimHDDocRef
TRUNCATE TABLE TCNTPdtIntDT
TRUNCATE TABLE TCNTPdtIntDTBch
TRUNCATE TABLE TCNTPdtLocSeq
TRUNCATE TABLE TCNTPdtPmtCB
TRUNCATE TABLE TCNTPdtPmtCG
TRUNCATE TABLE TCNTPdtPmtDT
TRUNCATE TABLE TCNTPdtPmtDTLot
TRUNCATE TABLE TCNTPdtPmtHD
TRUNCATE TABLE TCNTPdtPmtHD_L
TRUNCATE TABLE TCNTPdtPmtHDBch
TRUNCATE TABLE TCNTPdtPmtHDChn
TRUNCATE TABLE TCNTPdtPmtHDCst
TRUNCATE TABLE TCNTPdtPmtHDCstLev
TRUNCATE TABLE TCNTPdtPmtHDPay
TRUNCATE TABLE TCNTPdtPmtHDSeq
TRUNCATE TABLE TCNTPdtPrice4PDT
TRUNCATE TABLE TCNTPdtReqBchDT
TRUNCATE TABLE TCNTPdtReqBchHD
TRUNCATE TABLE TCNTPdtReqBchHDDocRef
TRUNCATE TABLE TCNTPdtReqHqDT
TRUNCATE TABLE TCNTPdtReqHqHD
TRUNCATE TABLE TCNTPdtReqHqHDDocRef
TRUNCATE TABLE TCNTPdtReqMgtDT
TRUNCATE TABLE TCNTPdtReqMgtHD
TRUNCATE TABLE TCNTPdtReqSplDT
TRUNCATE TABLE TCNTPdtReqSplHD
TRUNCATE TABLE TCNTPdtReqSplHDDocRef
TRUNCATE TABLE TCNTPdtReqSplHDSpl
TRUNCATE TABLE TCNTPdtSet
TRUNCATE TABLE TCNTPdtStkBal
TRUNCATE TABLE TCNTPdtStkCrd
TRUNCATE TABLE TCNTPdtStkCrdME
TRUNCATE TABLE TCNTPdtTbiDT
TRUNCATE TABLE TCNTPdtTbiHD
TRUNCATE TABLE TCNTPdtTbiHDRef
TRUNCATE TABLE TCNTPdtTboDT
TRUNCATE TABLE TCNTPdtTboHD
TRUNCATE TABLE TCNTPdtTboHDDocRef
TRUNCATE TABLE TCNTPdtTboHDRef
TRUNCATE TABLE TCNTPdtTwiDT
TRUNCATE TABLE TCNTPdtTwiHD
TRUNCATE TABLE TCNTPdtTwiHDRef
TRUNCATE TABLE TCNTPdtTwoDT
TRUNCATE TABLE TCNTPdtTwoHD
TRUNCATE TABLE TCNTPdtTwoHDRef
TRUNCATE TABLE TCNTPdtTwxDT
TRUNCATE TABLE TCNTPdtTwxHD
TRUNCATE TABLE TCNTPdtTwxHDRef
TRUNCATE TABLE TCNTQaDT
TRUNCATE TABLE TCNTQaDTAns
TRUNCATE TABLE TCNTQaHD

--FN
TRUNCATE TABLE TFNMBank
TRUNCATE TABLE TFNMBank_L

--TRUNCATE TABLE TFNMBankNote
--TRUNCATE TABLE TFNMBankNote_L

TRUNCATE TABLE TFNMBnkDepType
TRUNCATE TABLE TFNMBnkDepType_L
TRUNCATE TABLE TFNMBookBank
TRUNCATE TABLE TFNMBookBank_L
TRUNCATE TABLE TFNMCouponType
TRUNCATE TABLE TFNMCouponType_L

--TRUNCATE TABLE TFNMCreditCard
--TRUNCATE TABLE TFNMCreditCard_L
--TRUNCATE TABLE TFNMCreditCardBIN


TRUNCATE TABLE TFNMEdc
TRUNCATE TABLE TFNMEdc_L
TRUNCATE TABLE TFNMInstallment
TRUNCATE TABLE TFNMInstallment_L
TRUNCATE TABLE TFNMInstallmentSub
TRUNCATE TABLE TFNMRcv
TRUNCATE TABLE TFNMRcv_L
TRUNCATE TABLE TFNMRcvSpc
TRUNCATE TABLE TFNMRcvSpc_BK
TRUNCATE TABLE TFNTBnkDplDT
TRUNCATE TABLE TFNTBnkDplHD
TRUNCATE TABLE TFNTCouponDT
TRUNCATE TABLE TFNTCouponDTHis
TRUNCATE TABLE TFNTCouponHD
TRUNCATE TABLE TFNTCouponHD_L
TRUNCATE TABLE TFNTCouponHDBch
--LK
TRUNCATE TABLE TLKMCar
TRUNCATE TABLE TLKMCarInterBA
TRUNCATE TABLE TLKMCst
TRUNCATE TABLE TLKMCstBch
TRUNCATE TABLE TLKMCstShp
TRUNCATE TABLE TLKMErrMsg
TRUNCATE TABLE TLKMLMSShop
TRUNCATE TABLE TLKMMapping
TRUNCATE TABLE TLKMPdt
TRUNCATE TABLE TLKMPdt_L
TRUNCATE TABLE TLKMPdtBar
TRUNCATE TABLE TLKMPdtCategory
TRUNCATE TABLE TLKMPdtCatInfo
TRUNCATE TABLE TLKMPdtCatInfo_L
TRUNCATE TABLE TLKMPdtPackSize
TRUNCATE TABLE TLKMPdtUnit
TRUNCATE TABLE TLKMPdtUnit_L
TRUNCATE TABLE TLKTHistory
TRUNCATE TABLE TLKTLmsTxnHD
TRUNCATE TABLE TLKTLogHis
TRUNCATE TABLE TLKTPdtAdjPriDT
TRUNCATE TABLE TLKTPdtAdjPriHD
TRUNCATE TABLE TLKTPdtSet
TRUNCATE TABLE TLKTSalDoc2SAP
TRUNCATE TABLE TLKTShiftLMS
--PS
TRUNCATE TABLE TPSTDiscPolicy
TRUNCATE TABLE TPSTSalDT
TRUNCATE TABLE TPSTSalDTDis
TRUNCATE TABLE TPSTSalDTSet
TRUNCATE TABLE TPSTSalDTSN
TRUNCATE TABLE TPSTSalHD
TRUNCATE TABLE TPSTSalHDCst
TRUNCATE TABLE TPSTSalHDDis
TRUNCATE TABLE TPSTSalHDDocRef
TRUNCATE TABLE TPSTSalHDTag
TRUNCATE TABLE TPSTSalPD
TRUNCATE TABLE TPSTSalRC
TRUNCATE TABLE TPSTSalRCSpc
TRUNCATE TABLE TPSTShiftDT
TRUNCATE TABLE TPSTShiftEvent
TRUNCATE TABLE TPSTShiftHD
TRUNCATE TABLE TPSTShiftSKeyBN
TRUNCATE TABLE TPSTShiftSKeyRcv
TRUNCATE TABLE TPSTShiftSLastDoc
TRUNCATE TABLE TPSTShiftSSumRcv
TRUNCATE TABLE TPSTSlipEJ
TRUNCATE TABLE TPSTTaxDT
TRUNCATE TABLE TPSTTaxDTDis
TRUNCATE TABLE TPSTTaxHD
TRUNCATE TABLE TPSTTaxHDAddress
TRUNCATE TABLE TPSTTaxHDCst
TRUNCATE TABLE TPSTTaxHDDis
TRUNCATE TABLE TPSTTaxHDDocRef
TRUNCATE TABLE TPSTTaxNo
TRUNCATE TABLE TPSTTaxRC
TRUNCATE TABLE TPSTVoidDT
TRUNCATE TABLE TPSTVoidDTDis
--RG

-- Clear License  ถ้าต้องการเคลียร์เฉพาะข้อมูลที่ทดสอบให้ปิด ถ้าเคลียร์ แบบตั้งใหม่ โดยเริ่ม ลงทะเบียนใหม้ให้เปิด
-- Line 331-339

--TRUNCATE TABLE TRGMPdt
--TRUNCATE TABLE TRGSFuncDTLic
--TRUNCATE TABLE TRGSMenuLic
--TRUNCATE TABLE TRGSMenuLic_BK
--TRUNCATE TABLE TRGSMenuLic_BK_2
--TRUNCATE TABLE TRGTAutoNumber
--TRUNCATE TABLE TRGTCstKey
--TRUNCATE TABLE TRGTLicKey
--TRUNCATE TABLE TRGTPdtSet

--End Clear License  


--RPS

--TRUNCATE TABLE TRPSRptFormat
--TRUNCATE TABLE TRPSRptFormat_L

--RPT
TRUNCATE TABLE TRPTCstForcastByCar
TRUNCATE TABLE TRPTxHisSplPayment
--SV
TRUNCATE TABLE TSVMCar
TRUNCATE TABLE TSVMCarInfo
TRUNCATE TABLE TSVMCarInfo_L
TRUNCATE TABLE TSVMPdtCar
TRUNCATE TABLE TSVMPos
TRUNCATE TABLE TSVMPos_L
TRUNCATE TABLE TSVTBookDT
TRUNCATE TABLE TSVTBookDTSet
TRUNCATE TABLE TSVTBookHD
TRUNCATE TABLE TSVTBookHDDocRef
TRUNCATE TABLE TSVTCstFollow
TRUNCATE TABLE TSVTJob1ReqDT
TRUNCATE TABLE TSVTJob1ReqDTDis
TRUNCATE TABLE TSVTJob1ReqDTSet
TRUNCATE TABLE TSVTJob1ReqHD
TRUNCATE TABLE TSVTJob1ReqHDCst
TRUNCATE TABLE TSVTJob1ReqHDDis
TRUNCATE TABLE TSVTJob1ReqHDDocRef
TRUNCATE TABLE TSVTJob2OrdDT
TRUNCATE TABLE TSVTJob2OrdDTDis
TRUNCATE TABLE TSVTJob2OrdDTSet
TRUNCATE TABLE TSVTJob2OrdHD
TRUNCATE TABLE TSVTJob2OrdHDCst
TRUNCATE TABLE TSVTJob2OrdHDDis
TRUNCATE TABLE TSVTJob2OrdHDDocRef
TRUNCATE TABLE TSVTJob3ChkDT
TRUNCATE TABLE TSVTJob3ChkDTAns
TRUNCATE TABLE TSVTJob3ChkHD
TRUNCATE TABLE TSVTJob3ChkHDDocRef
TRUNCATE TABLE TSVTJob4ApvDT
TRUNCATE TABLE TSVTJob4ApvDTAns
TRUNCATE TABLE TSVTJob4ApvHD
TRUNCATE TABLE TSVTJob4ApvHDDocRef
TRUNCATE TABLE TSVTJob5ScoreDT
TRUNCATE TABLE TSVTJob5ScoreDTAns
TRUNCATE TABLE TSVTJob5ScoreHD
TRUNCATE TABLE TSVTJob5ScoreHDDocRef
TRUNCATE TABLE TSVTPdtSet
TRUNCATE TABLE TSVTPdtSetChk
TRUNCATE TABLE TSVTSalTwoDis
TRUNCATE TABLE TSVTSalTwoDT
TRUNCATE TABLE TSVTSalTwoDTSet
TRUNCATE TABLE TSVTSalTwoHD
TRUNCATE TABLE TSVTSalTwoHDCst
TRUNCATE TABLE TSVTSalTwoHDDocRef

--TCNTConfigSpc
TRUNCATE TABLE TCNTConfigSpc

-- TRUNCATE TABLE TCNTUrlObjectLogin;
-- DELETE TCNTUrlObject WHERE FTUrlKey NOT IN('REG','SLA','PAPD','BACKOFFICE');
-- UPDATE TCNTUrlObject SET FNUrlSeq = 1 WHERE FTUrlKey = 'REG';
-- UPDATE TCNTUrlObject SET FNUrlSeq = 2 WHERE FTUrlKey = 'SLA';
-- UPDATE TCNTUrlObject SET FNUrlSeq = 3 WHERE FTUrlKey = 'PAPD';

--User loin for register (Def User)



-- Clear User License  
--ถ้าต้องการเคลียร์เฉพาะข้อมูลที่ทดสอบให้ปิด ถ้าเคลียร์ แบบตั้งใหม่ โดยเริ่ม ลงทะเบียนใหม้ให้เปิด
--Line 414-426

--DELETE TCNMUser WHERE FTUsrCode != '00001';
--DELETE TCNMUser_L WHERE FTUsrCode != '00001';
--DELETE TCNMUsrActRole WHERE FTUsrCode != '00001';
--DELETE TCNMUsrLogin WHERE FTUsrCode != '00001';
--DELETE TCNMUsrRole WHERE FTRolCode != '00001';
--DELETE TCNMUsrRole_L WHERE FTRolCode != '00001';
--DELETE TCNMUsrRoleChain WHERE FTRolCode != '00001';

--DELETE TCNMVatRate WHERE FTVatCode != '00001';

--DELETE TCNTUsrFuncRpt WHERE FTRolCode != '00001';
--DELETE TCNTUsrGroup WHERE FTUsrCode != '00001';
--DELETE TCNTUsrMenu WHERE FTRolCode != '00001';

--End -- Clear User License  



--req--
--DELETE TFNMRate WHERE FTRteCode !='THB';
--DELETE TFNMRate_L WHERE FTRteCode !='THB';
--DELETE TFNMRateUnit WHERE FTRteCode !='THB';



--------------------------------------------------------------------------




